# Exported from Render on 2024-07-13T13:57:39Z
services:
  - type: web
    name: bun-docker
    runtime: docker
    repo: https://github.com/bldulam1/bun-docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
